trigger:
  branches:
    include:
    - main

jobs:
- job: Build
  pool:
    vmImage: ubuntu-latest
  steps:
    - task: Bash@3
      displayName: 'Run script'
      inputs:
        targetType: filePath
        filePath: script.sh
        arguments: arg1 arg2 "arg 3" arg\ 4
