trigger:
  branches:
    include:
    - main

jobs:
- job: Build
  pool:
    vmImage: ubuntu-latest
  steps:
    - bash: cat /etc/cgconfig.conf
    - bash: cat /etc/cgrules.conf
#     - bash: cat /proc/cgroups
#     - bash: cat /sys/fs/cgroup/cgroup.controllers
    - bash: cat /etc/default/grub.d/40-azuredevops.cfg
    - bash: /etc/docker/daemon.json
